# load XDF file
#dfDiscovery <- rxImport(inData = "./data/DiscoveryAgentsRecoded.xdf")

# load the data form SQL Server
sConnection <- "Driver=SQL Server;Server=FL-TPA-BI-01.alg.local;Database=Amerilife_STG;Trusted_Connection=TRUE"
sqlTableName <- "staging.SSAS_Discovery_Recoded"

# Summarize the data by Agent 
sQuery <- "
SELECT  [pk] = MIN([pk])
,[Agent] = MIN([Agent])
,[NPN]
,[CRMGender] = MIN([CRMGender])
,[CRMCounty] = MIN([CRMCounty])
,[CRMState] = MIN([CRMState])
,[CRMZipCode] = MIN([CRMZipCode])
,[HasKits] = MAX([HasKits])
,[HasContracts] = MAX([HasContracts])
,[IsDirectContract] = max(isDirectContract)
,[HasCommissionPayments] = MAX([HasCommissionPayments])
,[DSCPrimaryAddressType] = MIN([DSCPrimaryAddressType])
,[DSCPrimaryCounty] = MIN([DSCPrimaryCounty])
,[DSCPrimaryMetropolitanArea] = MIN([DSCPrimaryMetropolitanArea])
,[DSCPrimaryZipCode] = MIN([DSCPrimaryZipCode])
,[DSCPrimaryZipCode3DigitSectional] = MIN([DSCPrimaryZipCode3DigitSectional])
,[DSCDateOfBirthYear] = MIN([DSCDateOfBirthYear])
,[DSCGenderCode] = MIN([DSCGenderCode])
,[DSCAgentLicenseTypeHealth] = MIN([DSCAgentLicenseTypeHealth])
,[DSCAgentLicenseTypeLife] = MIN([DSCAgentLicenseTypeLife])
,[DSCAgentLicenseTypeVariableProducts] = MIN([DSCAgentLicenseTypeVariableProducts])
,[DSCAgentLicenseTypePropertyCasualty] = MIN([DSCAgentLicenseTypePropertyCasualty])
,[DSCNumberStateLicensesHealth] = MIN([DSCNumberStateLicensesHealth])
,[DSCNumberStateLicensesLife] = MIN([DSCNumberStateLicensesLife])
,[DSCNumberStateLicensesVariableProducts] = MIN([DSCNumberStateLicensesVariableProducts])
,[DSCNumberStateLicensesPropertyCasualty] = MIN([DSCNumberStateLicensesPropertyCasualty])
,[DSCStateLicensedCount] = MIN([DSCStateLicensedCount])
,[DSCSellsRetirementPlanProducts] = MIN([DSCSellsRetirementPlanProducts])
,[DSCCarrierAppointments] = MIN([DSCCarrierAppointments])
,[DSCAppointmentCount] = MIN([DSCAppointmentCount])
,[DSCYearsOfExperience] = MIN([DSCYearsOfExperience])
,[DSCEarliestAppointmentDate] = MIN([DSCEarliestAppointmentDate])
,[DSCDuallyLicensed] = MIN([DSCDuallyLicensed])
,[DSCInCRD] = MIN([DSCInCRD])
,[DSCRIAAffiliation] = MIN([DSCRIAAffiliation])
,[DSCBDRIARep] = MIN([DSCBDRIARep])
,[DSCBrokerDealerAffiliation] = MIN([DSCBrokerDealerAffiliation])
,[12MonthRevenueFromContractCompleted] = SUM([12MonthRevenueFromContractCompleted])
,[12MonthRevenueFromContractEffective] = SUM([12MonthRevenueFromContractEffective])
,[12MonthFromFirstRevenue] = SUM([12MonthFromFirstRevenue])
,[24MonthRevenueFromContractCompleted] = SUM([24MonthRevenueFromContractCompleted])
,[24MonthRevenueFromContractEffective] = SUM([24MonthRevenueFromContractEffective])
,[24MonthFromFirstRevenue] = SUM([24MonthFromFirstRevenue])
,[RevenueSinceInception] = SUM([RevenueSinceInception])
,[PolicyCount] = SUM([PolicyCount])
,[Payments] = SUM([Payments])
,[Commission] = SUM([Commission])
,[PaymentCountSinceInception] = SUM([PaymentCountSinceInception])
,RecordCount = COUNT(*)
FROM [staging].[SSAS_Discovery_Recoded]
group by NPN
"

sqlDataTable <- RxSqlServerData(connectionString = sConnection,
    sqlQuery = sQuery)
    #table = sqlTableName)
df <- rxImport(inData = sqlDataTable,
    rowsPerRead = 10000,
    stringsAsFactors = TRUE)

# Common libraries
library(ggplot2)
library(car)
library(dplyr)
library(corrplot)
library(gplots)
library(gridExtra)
library(cowplot)

# Set the row names to the pk from SQL
row.names(df) <- df$pk
#rxGetVarInfo(df)
str(df)
summary(df)

# Single attribute analysis

#summary(df$PaymentCountSinceInception)
#summary(df$"12MonthRevenueFromContractCompleted")
#summary(df$"24MonthRevenueFromContractCompleted")

# Commissions
summary(df$Commission)

# All
dfPlot <- df %>%
select(Commission)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 1000, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Frequency of Lifetime Commissions generated by an Agent") +
labs(x = "Total Commissions", y = "Frequency")

CommissionBinned <-
recode(df$Commission, "-30000:-5000='Debt 5 to 30k';-4999.99:-500='Debt 500 to 5k';
    -499.99:0='Small Debt';0.01:100='$0 to $100'; 100.01:200='$100 to $200';
    200.01:300='$200 to $300';300.01:400='$300 to $400';400.01:500='$400 to $500';
    500.01:1000 = '$500 to $1k';1000.01:5000 = '$1k to $5k';else = 'Above $5k' ",
    as.factor.result = TRUE,
    levels = c('Debt 5 to 30k', 'Debt 500 to 5k', 'Small Debt', '$0 to $100', '$100 to $200',
    '$200 to $300', '$300 to $400', '$400 to $500', '$500 to $1k', '$1k to $5k', 'Above $5k'))
dfBinned <- data.frame(table(CommissionBinned))
#barplot(table(CommissionBinned))
ggplot(data = dfBinned, aes(x = CommissionBinned, y = Freq)) +
geom_bar(stat = "identity") +
ylim(0,45000) +
ggtitle("Frequency of Lifetime Commissions and Debt\ngenerated by an Agent") +
labs(x = "Total Commissions", y = "Count of Agents") +
theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
geom_text(aes(label=Freq), vjust=-0.2, color="darkgreen", size = 3)

# Between $1 and $1000
dfPlot <- df %>%
select(Commission) %>%
filter(Commission <= 1000 & Commission > 0)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 10, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Frequency of Lifetime Commissions from $1 up to $1,000\n generated by an Agent") +
labs(x = "Total Commissions", y = "Frequency")

# Above $5000
dfPlot <- df %>%
select(Commission) %>%
filter(Commission > 5000)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 5000, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Frequency of Lifetime Commissions from $5000 and up\n generated by an Agent") +
labs(x = "Total Commissions", y = "Frequency")

# Between $5000 and $50000
dfPlot <- df %>%
select(Commission) %>%
filter(Commission > 5000 & Commission <= 50000)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 5000, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Frequency of Lifetime Commissions from $5000 to $50,000\n generated by an Agent") +
labs(x = "Total Commissions", y = "Frequency")

# Between $5000 and $50000 - Counts - Stacked by Direct vs Upline
dfPlot <- df %>%
select(c(Commission, IsDirectContract)) %>%
filter(Commission > 5000 & Commission <= 50000)
ggplot(data = dfPlot, aes(x = Commission, y = ..count.., fill = IsDirectContract)) +
geom_histogram(binwidth = 5000, color = "grey60", size = 0.2) +
ggtitle("Frequency of Lifetime Commissions from $5000 to $50,000\n generated by an Agent") +
labs(x = "Total Commissions", y = "Counts")

# Between $500 and $2,500
dfPlot <- df %>%
select(Commission) %>%
filter(Commission <= 2500 & Commission >= 500)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 100, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Frequency of Lifetime Commissions from $500 up to $2,500\n generated by an Agent") +
labs(x = "Total Commissions", y = "Frequency")

# Between $500 and $2,500 - Counts - Stacked by Direct vs Upline
dfPlot <- df %>%
select(c(Commission, IsDirectContract)) %>%
filter(Commission <= 2500 & Commission >= 500)
ggplot(data = dfPlot, aes(x = Commission, y = ..count.., fill = IsDirectContract)) +
geom_histogram(binwidth = 100, color = "grey60", size = 0.2) +
ggtitle("Frequency of Lifetime Commissions from $500 up to $2,500\n generated by an Agent") +
labs(x = "Total Commissions", y = "Count of Agents")

# Between $500 and $2,500 - Counts - Stacked by Direct vs Upline
dfPlot <- df %>% select(c(Commission, IsDirectContract)) %>% filter(Commission <= 2500 & Commission >= 500)
ggplot(data = dfPlot, aes(x = Commission, y = ..count.., fill = IsDirectContract)) +
geom_histogram(binwidth = 100, color = "grey60", size = 0.2) +
ggtitle("Counts of Lifetime Commissions from $500 up to $2,500\n generated by an Agent") +
labs(x = "Total Commissions", y = "Counts")

# Agents with debt
dfPlot <- df %>%
select(Commission) %>%
filter(Commission < 0)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 2000, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Counts of Lifetime Debts generated by an Agent\nThese Agents never produced revenue only debt") +
labs(x = "Total Debt", y = "Frequesncy")

# Agents with debt - Counts
dfPlot <- df %>%
select(Commission) %>%
filter(Commission < 0)
ggplot(data = dfPlot, aes(x = Commission, y = ..count..)) +
geom_histogram(binwidth = 2000, color = "grey60", size = 0.2) +
ggtitle("Counts of Lifetime Debts generated by an Agent\nThese Agents never produced revenue only debt") +
labs(x = "Total Debt", y = "Counts")

###############################################################################################
# 12 Month Revenue from Contract Completed
summary(df$`12MonthRevenueFromContractCompleted`)

# All
dfPlot <- df %>%
select(`12MonthRevenueFromContractCompleted`)
ggplot(data = dfPlot, aes(x = `12MonthRevenueFromContractCompleted`, y = ..density..)) +
geom_histogram(binwidth = 1000, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Frequency of First 12 Month Revenue From CC\ngenerated by an Agent") +
labs(x = "First 12 Month Revenue From CC", y = "Frequency")

CommissionBinned <-
recode(df$Commission, "-30000:-5000='Debt 5 to 30k';-4999.99:-500='Debt 500 to 5k';
    -499.99:0='Small Debt';0.01:100='$0 to $100'; 100.01:200='$100 to $200';
    200.01:300='$200 to $300';300.01:400='$300 to $400';400.01:500='$400 to $500';
    500.01:1000 = '$500 to $1k';1000.01:5000 = '$1k to $5k';else = 'Above $5k' ",
    as.factor.result = TRUE,
    levels = c('Debt 5 to 30k', 'Debt 500 to 5k', 'Small Debt', '$0 to $100', '$100 to $200',
    '$200 to $300', '$300 to $400', '$400 to $500', '$500 to $1k', '$1k to $5k', 'Above $5k'))
dfBinned <- data.frame(table(CommissionBinned))
#barplot(table(CommissionBinned))
ggplot(data = dfBinned, aes(x = CommissionBinned, y = Freq)) +
geom_bar(stat = "identity") +
ylim(0, 45000) +
ggtitle("Frequency of Lifetime Commissions and Debt\ngenerated by an Agent") +
labs(x = "Total Commissions", y = "Count of Agents") +
theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
geom_text(aes(label = Freq), vjust = -0.2, color = "darkgreen", size = 3)

# Between $1 and $1000
dfPlot <- df %>%
select(Commission) %>%
filter(Commission <= 1000 & Commission > 0)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 10, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Frequency of Lifetime Commissions from $1 up to $1,000\n generated by an Agent") +
labs(x = "Total Commissions", y = "Frequency")

# Above $5000
dfPlot <- df %>%
select(Commission) %>%
filter(Commission > 5000)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 5000, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Frequency of Lifetime Commissions from $5000 and up\n generated by an Agent") +
labs(x = "Total Commissions", y = "Frequency")

# Between $5000 and $50000
dfPlot <- df %>%
select(Commission) %>%
filter(Commission > 5000 & Commission <= 50000)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 5000, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Frequency of Lifetime Commissions from $5000 to $50,000\n generated by an Agent") +
labs(x = "Total Commissions", y = "Frequency")

# Between $5000 and $50000 - Counts - Stacked by Direct vs Upline
dfPlot <- df %>%
select(c(Commission, IsDirectContract)) %>%
filter(Commission > 5000 & Commission <= 50000)
ggplot(data = dfPlot, aes(x = Commission, y = ..count.., fill = IsDirectContract)) +
geom_histogram(binwidth = 5000, color = "grey60", size = 0.2) +
ggtitle("Frequency of Lifetime Commissions from $5000 to $50,000\n generated by an Agent") +
labs(x = "Total Commissions", y = "Counts")

# Between $500 and $2,500
dfPlot <- df %>%
select(Commission) %>%
filter(Commission <= 2500 & Commission >= 500)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 100, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Frequency of Lifetime Commissions from $500 up to $2,500\n generated by an Agent") +
labs(x = "Total Commissions", y = "Frequency")

# Between $500 and $2,500 - Counts - Stacked by Direct vs Upline
dfPlot <- df %>%
select(c(Commission, IsDirectContract)) %>%
filter(Commission <= 2500 & Commission >= 500)
ggplot(data = dfPlot, aes(x = Commission, y = ..count.., fill = IsDirectContract)) +
geom_histogram(binwidth = 100, color = "grey60", size = 0.2) +
ggtitle("Frequency of Lifetime Commissions from $500 up to $2,500\n generated by an Agent") +
labs(x = "Total Commissions", y = "Count of Agents")

# Between $500 and $2,500 - Counts - Stacked by Direct vs Upline
dfPlot <- df %>% select(c(Commission, IsDirectContract)) %>% filter(Commission <= 2500 & Commission >= 500)
ggplot(data = dfPlot, aes(x = Commission, y = ..count.., fill = IsDirectContract)) +
geom_histogram(binwidth = 100, color = "grey60", size = 0.2) +
ggtitle("Counts of Lifetime Commissions from $500 up to $2,500\n generated by an Agent") +
labs(x = "Total Commissions", y = "Counts")

# Agents with debt
dfPlot <- df %>%
select(Commission) %>%
filter(Commission < 0)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 2000, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Counts of Lifetime Debts generated by an Agent\nThese Agents never produced revenue only debt") +
labs(x = "Total Debt", y = "Frequesncy")

# Agents with debt - Counts
dfPlot <- df %>%
select(Commission) %>%
filter(Commission < 0)
ggplot(data = dfPlot, aes(x = Commission, y = ..count..)) +
geom_histogram(binwidth = 2000, color = "grey60", size = 0.2) +
ggtitle("Counts of Lifetime Debts generated by an Agent\nThese Agents never produced revenue only debt") +
labs(x = "Total Debt", y = "Counts")




# RevenueSinceInception
summary(df$RevenueSinceInception)
dfPlot <- df %>%
select(RevenueSinceInception) %>%
filter(RevenueSinceInception <= 200 & RevenueSinceInception >= 0)
ggplot(data = dfPlot, aes(x = RevenueSinceInception)) +
geom_histogram(binwidth = 5)


# Bi-variate analysis of attributes

# Select a subset of the columns
#dfBase <- df %>%
#select(starts_with("CRM"), starts_with("Has"), starts_with("DSC"), contains("Revenue"), 
    #PolicyCount, Payments, Commission, PaymentCountSinceInception, RecordCount)
dfBase <- df %>%
select(CRMGender, CRMState, DSCPrimaryAddressType, DSCNumberStateLicensesHealth,
DSCNumberStateLicensesLife, DSCNumberStateLicensesVariableProducts, 
DSCNumberStateLicensesPropertyCasualty, Commission)

#save(dfBase, file = "./data/dfBase.Rda")

scatterplotMatrix(dfBase[,], diagonal = "histogram")
corrplot.mixed(corr = cor(dfBase[, c( 4:8 )]),
    upper = "ellipse", tl.pos = "lt",
    col = colorpanel(50, "red", "gray60", "blue4"))
