# load XDF file
#dfDiscovery <- rxImport(inData = "./data/DiscoveryAgentsRecoded.xdf")

# load the data form SQL Server
sConnection <- "Driver=SQL Server;Server=FL-TPA-BI-01.alg.local;Database=Amerilife_STG;Trusted_Connection=TRUE"
sqlTableName <- "staging.SSAS_Discovery_Recoded"

# Summarize the data by Agent 
sQuery <- "
SELECT  [pk] = MIN([pk])
,[Agent] = MIN([Agent])
,[NPN]
,[CRMGender] = MIN([CRMGender])
,[CRMCounty] = MIN([CRMCounty])
,[CRMState] = MIN([CRMState])
,[CRMZipCode] = MIN([CRMZipCode])
,[HasKits] = MAX([HasKits])
,[HasContracts] = MAX([HasContracts])
,[HasCommissionPayments] = MAX([HasCommissionPayments])
,[DSCPrimaryAddressType] = MIN([DSCPrimaryAddressType])
,[DSCPrimaryCounty] = MIN([DSCPrimaryCounty])
,[DSCPrimaryMetropolitanArea] = MIN([DSCPrimaryMetropolitanArea])
,[DSCPrimaryZipCode] = MIN([DSCPrimaryZipCode])
,[DSCPrimaryZipCode3DigitSectional] = MIN([DSCPrimaryZipCode3DigitSectional])
,[DSCDateOfBirthYear] = MIN([DSCDateOfBirthYear])
,[DSCGenderCode] = MIN([DSCGenderCode])
,[DSCAgentLicenseTypeHealth] = MIN([DSCAgentLicenseTypeHealth])
,[DSCAgentLicenseTypeLife] = MIN([DSCAgentLicenseTypeLife])
,[DSCAgentLicenseTypeVariableProducts] = MIN([DSCAgentLicenseTypeVariableProducts])
,[DSCAgentLicenseTypePropertyCasualty] = MIN([DSCAgentLicenseTypePropertyCasualty])
,[DSCNumberStateLicensesHealth] = MIN([DSCNumberStateLicensesHealth])
,[DSCNumberStateLicensesLife] = MIN([DSCNumberStateLicensesLife])
,[DSCNumberStateLicensesVariableProducts] = MIN([DSCNumberStateLicensesVariableProducts])
,[DSCNumberStateLicensesPropertyCasualty] = MIN([DSCNumberStateLicensesPropertyCasualty])
,[DSCStateLicensedCount] = MIN([DSCStateLicensedCount])
,[DSCSellsRetirementPlanProducts] = MIN([DSCSellsRetirementPlanProducts])
,[DSCCarrierAppointments] = MIN([DSCCarrierAppointments])
,[DSCAppointmentCount] = MIN([DSCAppointmentCount])
,[DSCYearsOfExperience] = MIN([DSCYearsOfExperience])
,[DSCEarliestAppointmentDate] = MIN([DSCEarliestAppointmentDate])
,[DSCDuallyLicensed] = MIN([DSCDuallyLicensed])
,[DSCInCRD] = MIN([DSCInCRD])
,[DSCRIAAffiliation] = MIN([DSCRIAAffiliation])
,[DSCBDRIARep] = MIN([DSCBDRIARep])
,[DSCBrokerDealerAffiliation] = MIN([DSCBrokerDealerAffiliation])
,[12MonthRevenueFromContractCompleted] = SUM([12MonthRevenueFromContractCompleted])
,[12MonthRevenueFromContractEffective] = SUM([12MonthRevenueFromContractEffective])
,[12MonthFromFirstRevenue] = SUM([12MonthFromFirstRevenue])
,[24MonthRevenueFromContractCompleted] = SUM([24MonthRevenueFromContractCompleted])
,[24MonthRevenueFromContractEffective] = SUM([24MonthRevenueFromContractEffective])
,[24MonthFromFirstRevenue] = SUM([24MonthFromFirstRevenue])
,[RevenueSinceInception] = SUM([RevenueSinceInception])
,[PolicyCount] = SUM([PolicyCount])
,[Payments] = SUM([Payments])
,[Commission] = SUM([Commission])
,[PaymentCountSinceInception] = SUM([PaymentCountSinceInception])
,RecordCount = COUNT(*)
FROM [staging].[SSAS_Discovery_Recoded]
group by NPN
"

sqlDataTable <- RxSqlServerData(connectionString = sConnection,
    sqlQuery = sQuery)
    #table = sqlTableName)
df <- rxImport(inData = sqlDataTable,
    rowsPerRead = 10000,
    stringsAsFactors = TRUE)

# Common libraries
library(ggplot2)
library(car)
library(dplyr)
library(corrplot)
library(gplots)

# Set the row names to the pk from SQL
row.names(df) <- df$pk
#rxGetVarInfo(df)
str(df)
summary(df)

# Single attribute analysis

#summary(df$PaymentCountSinceInception)
#summary(df$"12MonthRevenueFromContractCompleted")
#summary(df$"24MonthRevenueFromContractCompleted")

# Commissions
summary(df$Commission)

# All
dfPlot <- df %>%
select(Commission)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 1000, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Frequency of Lifetime Commissions generated by an Agent") +
labs(x = "Total Commissions", y = "Frequency")

# Between $1 and $1000
dfPlot <- df %>%
select(Commission) %>%
filter(Commission <= 1000 & Commission > 0)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 10, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Frequency of Lifetime Commissions from $1 up to $1,000\n generated by an Agent") +
labs(x = "Total Commissions", y = "Frequency")

# Above $500
dfPlot <- df %>%
select(Commission) %>%
filter(Commission > 500)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 10000, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Frequency of Lifetime Commissions from $500 and up\n generated by an Agent") +
labs(x = "Total Commissions", y = "Frequency")

# Between $500 and $2,500
dfPlot <- df %>%
select(Commission) %>%
filter(Commission <= 2500 & Commission >= 500)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 100, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Frequency of Lifetime Commissions from $500 up to $2,500\n generated by an Agent") +
labs(x = "Total Commissions", y = "Frequency")

# Between $500 and $2,500 - Counts
dfPlot <- df %>%
select(Commission) %>%
filter(Commission <= 2500 & Commission >= 500)
ggplot(data = dfPlot, aes(x = Commission, y = ..count..)) +
geom_histogram(binwidth = 100, color = "grey60", size = 0.2) +
ggtitle("Counts of Lifetime Commissions from $500 up to $2,500\n generated by an Agent") +
labs(x = "Total Commissions", y = "Counts")

# Agents with debt
dfPlot <- df %>%
select(Commission) %>%
filter(Commission < 0)
ggplot(data = dfPlot, aes(x = Commission, y = ..density..)) +
geom_histogram(binwidth = 2000, color = "grey60", size = 0.2) +
geom_density(color = "red", size = 1) +
ggtitle("Counts of Lifetime Debts generated by an Agent\nThese Agents never produced revenue only debt") +
labs(x = "Total Debt", y = "Frequesncy")

# Agents with debt - Counts
dfPlot <- df %>%
select(Commission) %>%
filter(Commission < 0)
ggplot(data = dfPlot, aes(x = Commission, y = ..count..)) +
geom_histogram(binwidth = 2000, color = "grey60", size = 0.2) +
ggtitle("Counts of Lifetime Debts generated by an Agent\nThese Agents never produced revenue only debt") +
labs(x = "Total Debt", y = "Counts")


# RevenueSinceInception
summary(df$RevenueSinceInception)
dfPlot <- df %>%
select(RevenueSinceInception) %>%
filter(RevenueSinceInception <= 200 & RevenueSinceInception >= 0)
ggplot(data = dfPlot, aes(x = RevenueSinceInception)) +
geom_histogram(binwidth = 5)


# Bi-variate analysis of attributes

# Select a subset of the columns
#dfBase <- df %>%
#select(starts_with("CRM"), starts_with("Has"), starts_with("DSC"), contains("Revenue"), 
    #PolicyCount, Payments, Commission, PaymentCountSinceInception, RecordCount)
dfBase <- df %>%
select(CRMGender, CRMState, DSCPrimaryAddressType, DSCNumberStateLicensesHealth,
DSCNumberStateLicensesLife, DSCNumberStateLicensesVariableProducts, 
DSCNumberStateLicensesPropertyCasualty, Commission)

#save(dfBase, file = "./data/dfBase.Rda")

scatterplotMatrix(dfBase[,], diagonal = "histogram")
corrplot.mixed(corr = cor(dfBase[, c( 4:8 )]),
    upper = "ellipse", tl.pos = "lt",
    col = colorpanel(50, "red", "gray60", "blue4"))
